version: 2

builds:
  - binary: apilot
    main: ./apilot-cli
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/tangcent/apilot/apilot-cli/build.Version={{ .Version }} -X github.com/tangcent/apilot/apilot-cli/build.Date={{ .Date }}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "apilot-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
